In [2]:
from numpy import *

In [17]:
t1 = array([1,1,2,3,5,8])

# opérations en commun avec les chaînes de catactères
print( len(t1) )
print( t1[0] )
print( t1[1:] )

6
1
[1 2 3 5 8]


In [15]:
# opération spécifique aux tableaux : modification d'une cellule
t1[0] = 42
print(t1)

[42  1  2  3  5  8]


In [34]:
t2 = empty(1_000_000, float)
print(t2)
print(len(t2))

[  1.54514762e-316   0.00000000e+000   0.00000000e+000 ...,
   0.00000000e+000   0.00000000e+000   0.00000000e+000]
1000000


In [45]:
def zeros(taille):
    """
    :entrée taille: int
    :pré-cond: taille > 0
    :sortie t: tableau de float
    :post-cond: len(t) == taille,
                et t[i] = 0.0 pour tout i entre 0 et taille-1
    """
    t = empty(taille, float)
    i = 0
    while i < taille: # ou i <= taille-1
        t[i] = 0.0
        i = i+1
    return t

t3 = zeros(10000000)
print(t3)
print(len(t3))
        

[ 0.  0.  0. ...,  0.  0.  0.]
10000000


In [52]:
# en fait, la fonction zeros existe déjà
from numpy import *

t4 = zeros(10, int)
print(t4)

[0 0 0 0 0 0 0 0 0 0]


In [55]:
def suite_arithmétique(premier, raison, taille):
    """
    :entrée premier, raison, taille: int
    :pré-cond: taille > 0
    :sortie t: tableau d'int
    :post-cond: len(t) == taille, t[0] == premier
                t contient les 'taille' premiers éléments
                de la suite arithmétique
                de premier élément 'premier'
                et de raison 'raison'
    """
    t = empty(taille, int)
    i = 0
    while i < taille:
        t[i] = premier + raison*i
        i = i+1
    return t

print(suite_arithmétique(0,1,5))

[0 1 2 3 4]


In [60]:
def suite_arithmétique(premier, raison, taille):
    t = empty(taille, int)
    t[0] = premier
    i = 1
    while i < taille:
        t[i] = t[i-1] + raison
        i = i+1
    return t

print(suite_arithmétique(10,2,5))

[10 12 14 16 18]


In [64]:
def fibonacci(taille):
    """
    :entrée taille: int
    :pré-cond: taille ≥ 2
    :sortie t: tableau d'int
    :post-cond: ?
    """
    t = empty(taille, int)
    t[0] = 1
    t[1] = 1
    i = 2
    while i < taille:
        t[i] = t[i-1] + t[i-2]
        i = i+1
    return t

print( fibonacci(12) )
    

[  1   1   2   3   5   8  13  21  34  55  89 144]


In [66]:
def somme(t):
    """
    :entrée t: tableau de float
    :sortie s: float
    :post-cond: s est la somme des éléments de t
    """
    s = 0
    i = 0
    while i < len(t):
        s = s + t[i]
        i = i+1
    return s

def somme(t):
    """
    :entrée t: tableau de float
    :sortie s: float
    :post-cond: s est la somme des éléments de t
    """
    if len(t) == 0:
        s = 0
    else:
        s = t[0] + somme(t[1:])
    return s

print(somme(fibonacci(12)))
    

376


In [67]:
# note sur les chaînes de caractères

ts = array(["hi", "world"])
print(ts)
ts[0] = "anticonstitutionnellement"
print(ts)

['hi' 'world']
['antic' 'world']
