In [1]:
from numpy import *

In [2]:
def insere_dernier(t):
    """
    :entrée-sortie t: tableau de float
    :pré-cond: t est trié de la première à l'avant-dernière case
    :post-cond: t est totalement trié
    """
    vi = t[len(t)-1] # valeur à insérer
    i = len(t)-2
    while i >= 0  and  t[i] > vi:
        t[i+1] = t[i]
        i = i-1
    t[i+1] = vi
    
def tri_insertion(t):
    """
    :entrée-sortie t: tableau de float
    :post-cond: t est trié
    """
    l = 2
    while l <= len(t):
        insere_dernier(t[:l])
        l = l+1

a = array([1.0, 9.0, 3.0, 14.0, 7.0, 9.0])
print(a)
tri_insertion(a)
print(a)


[  1.   9.   3.  14.   7.   9.]
[  1.   3.   7.   9.   9.  14.]


In [3]:
def quick_sort(t):
    """
    :entrée-sortie t: tableau de float
    :post-cond: t est trié
    """
    if len(t) < 2:
        pass
    else:
        ipivot = partitionne(t)
        quick_sort(t[:ipivot])
        quick_sort(t[ipivot+1:])
    
def partitionne(t):
    """
    :entrée-sortie t: tableau de float
    :pré-cond: len(t) > 1:
    :sortie ip: int
    :post-cond: les valeurs de t ont changé de place
                t[:ip] ne contient que des valeurs <= t[ip]
                t[ip+1:] ne contient que des valeurs > t[ip]
    """
    p = t[0]
    i = 1
    j = len(t)-1
    while i <= j:
        while i <= j  and  t[i] <= p:
            i = i+1
        while j >= i  and t[j] > p:
            j = j-1
        if i < j:
            tmp = t[i]
            t[i] = t[j]
            t[j] = tmp
    t[0] = t[j]
    t[j] = p
    return j

a = array([99.0, 8.0, 3.0, 6.0, 14.0, 7.0, 9.0])
print(a)
quick_sort(a)
print(a)

[ 99.   8.   3.   6.  14.   7.   9.]
[  3.   6.   7.   8.   9.  14.  99.]
