In [1]:
from numpy import *
t = array([42])
print(t[1:])

[]


In [10]:
def moyenne(t):
    """
    :entrée t: tableau de float
    :pré-cond: /
    :sortie m: float
    :post-cond: m est la moyenne des éléments de t
    """
    if len(t) > 0:
        i = 0
        s = 0.0
        while i < len(t):
            s = s + t[i]
            i = i + 1
        m = s/len(t)
    else:
        m = 0.0
    return m

In [12]:
def minmax(t):
    """
    :entrée t: tableau de float
    :pré-cond: len(t) > 0
    :sortie min, max: float
    :post-cond: min est la plus petite valeur de t
                max est la plus grande valeur de t
    """
    min = t[0]
    max = t[0]
    i = 1
    while i < len(t):
        if t[i] > max:
            max = t[i]
        else:
            if t[i] < min:
                min = t[i]
        i = i+1
    return min, max

def minmax(t):
    if len(t) == 1:
        min = max = t[0]
    else:
        min, max = minmax(t[1:])
        if t[0] < min:
            min = t[0]
        if t[0] > max:
            max = t[0]
    return min, max


In [14]:
a = 42
b = a
a = a+1
print(a, b)

43 42


In [17]:
a = array([1,2,3])
b = a
a[0] = a[0]+1
print(a, b)

[2 2 3] [2 2 3]


In [10]:
def copie(te):
    """
    :entrée te: tableau de float
    :sortie ts: tableau de float
    :post-cond: len(ts) = len(te)
                 pour tout i < len(te), te[i] = ts[i]
    """
    ts = empty(len(te), float)
    i = 0
    while i < len(te):
        ts[i] = te[i]
        i = i+1
    return ts
    

In [13]:
def double(te):
    """
    :entrée te: tableau de float
    :sortie ts: tableau de float
    :post-cond: len(ts) = len(te) et pour tout i ts[i] = 2×te[i]
    """
    ts = empty(len(te), float)
    i = 0
    while i < len(te):
        ts[i] = 2*te[i]
        i = i+1
    return ts

a = array([1.0, 2.0, 3.0])
b = double(a)
print(a, b)

[ 1.  2.  3.] [ 2.  4.  6.]


In [3]:
def double_en_place(t):
    """
    :entrée-sortie t: tableau de float
    :post-cond: pour tout i tₛ[i] = 2×tₑ[i]
    """
    i = 0
    while i < len(t):
        t[i] = 2*t[i]
        i = i+1

a = array([1.0, 2.0, 3.0])
print(a)
double_en_place(a)
print(a)

[ 1.  2.  3.]
[ 2.  4.  6.]
