In [1]:
from numpy import *

# Algorithmes avec les paramètres d'entrée-sortie

In [2]:
def integre_en_place(t):
    """
    :entrée-sortie t: tableau de float
    :pré-cond: /
    :post-cond: pour tout i E [0, len(t)[
                tₛ[i] = somme pour j E [0, i] tₑ[j]
    """
    i = 1
    while i < len(t):
        t[i] = t[i] + t[i-1]
        i = i+1
        
a = array([7, 1, -1, 3, 5])     
print(a)
integre_en_place(a)
print(a)

[ 7  1 -1  3  5]
[ 7  8  7 10 15]


In [3]:
# en récursif

def integre_en_place(t):
    """
    :entrée-sortie t: tableau de float
    :pré-cond: /
    :post-cond: pour tout i E [0, len(t)[
                tₛ[i] = somme pour j E [0, i] tₑ[j]
    """
    if len(t) < 2:
        pass
    else:
        integre_en_place(t[:len(t)-1])
        t[len(t)-1] = t[len(t)-1] + t[len(t)-2]

In [4]:
def derive_en_place(t):
    """
    :entrée-sortie t: tableau de float
    :pré-cond: /
    :post-cond: pour tout i E [1, len(t)[
                tₛ[i] = tₑ[i] - tₑ[i-1]
                et tₛ[0] = tₑ[0]
    """
    i = len(t)-1
    while i > 0:
        t[i] = t[i] - t[i-1]
        i = i-1

derive_en_place(a)
print(a)

[ 7  1 -1  3  5]


# Recherche dans un tableau

In [5]:
def trouve_indice(t, val):
    """
    :entrée t: tableau de float
    :entrée val: float
    :sortie ival: int
    :post-cond: si val E t, t[ival] = val
                sinon ival = -1
    """
    ival = -1
    i = 0
    while i < len(t) and ival==-1:
        if t[i] == val:
            ival = i
        i = i+1
    return ival
    
#t=[ 2, 4, 3.14, 5, 2, 7]  val=4  -> ival=1
#t=[ 2, 4, 3.14, 5, 2, 7]  val=42 -> ival=-1
#t=[ 2, 4, 3.14, 5, 2, 7]  val=2  -> ival=4

In [6]:
# écriture récursive

def trouve_indice(t, val):
    if len(t) == 0:
        ival = -1
    else:
        if t[len(t)-1] == val:
            ival = len(t)-1
        else:
            ival = trouve_indice(t[:len(t)-1], val)
    return ival

Considérons maintenant un contrat plus spécifique,
dans lequel on impose au tableau d'être trié.

In [7]:
def trouve_indice_t(t, val):
    """
    :entrée t: tableau de float
    :entrée val: float
    :pré-cond: t est trié par ordre croissant
    :sortie ival: int
    :post-cond: si val E t, t[ival] = val
                sinon ival = -1
    """
    ival = -1
    i = 0
    while i < len(t) and t[i] <= val and ival==-1:
        if t[i] == val:
            ival = i
        i = i+1
    return ival

#t=[ 2, 4, 5, 12, 42, 101]  val=4   -> ival=1
#t=[ 2, 4, 5, 12, 42, 101]  val=13  -> ival=-1
#t=[ 2, 4, 5, 12, 42, 101]  val=102 -> ival=-1

La version ci-dessus améliore les performances dans certains cas,
mais dans le pire des cas on doit toujours parcourir la totalité du tableau.

On doit pouvoir mieux faire...